### ISSUE TITLE
Formal test for Application installation functionality

### ISSUE THREAD

**Issue by GoogleCodeExporter** [stko/oobd#126]
```
A formal test has to be written and applied to make sure the installation, 
update & remove functionality of the application software fulfills all 
requirements
```

Original issue reported on code.google.com by `steffen....@gmail.com` on 2 Nov 2013 at 1:45

**Comment by stko** [comment]
Half done (for Windows) - http://testlink.oobd.org/linkto.php?tprojectPrefix=OO&item=testsuite&id=32
