### ISSUE TITLE
OOBD-Desk / -Android crashes if using new function getLocalePrintf

### ISSUE THREAD

**Issue by GoogleCodeExporter** [stko/oobd#148]
```
In case of missing database file i.e. nrc_de_de.oodb the application 
hangs/crashes as newArray seems to be nil.

If/else conditions must be improved!
```

Original issue reported on code.google.com by `michael....@gmail.com` on 14 Jul 2014 at 10:10

**Comment by stko** [comment]
Nexulm, I guess the locale function is more reliable now

**Comment by stko** [comment]
Databases now passes the RF Tests for missing DB files or entries
