### ISSUE TITLE
OOBDesk combo box

### ISSUE THREAD

**Issue by nexulm** [stko/oobd#172]
Faulty order of combo box items. OOBD Android is OK, but the index item order of the Java OOBDesk combo box is faulty sorted.

**Comment by stko** [comment]
I can't reproduce the fault, for me it works with the content

content={"one","two","three","four","five","six"}

What are your parameters?

**Comment by nexulm** [comment]
See oobd.lua ModuleID here:

**Comment by stko** [comment]
Also bei mir sieht das so aus. Ist doch richtig, oder? Wo passiert denn bei Dir der Fehler: Schon bei der Darstellung selber oder erst, wenn bei einer Auswahl dann der Index- Wert abgerufen wird?


![image](https://cloud.githubusercontent.com/assets/4143790/11791480/8dc51648-a2a1-11e5-855c-6bff7c0bbbf6.png)

**Comment by stko** [comment]
So, ich hab auch noch mal im Quellcode geschnüffelt. Tatsächlich ist das in Android komplizierter umgesetzt als in OOBDesk. Scheint, als hätte das in Android ursprünglich auch nicht so funktioniert. Ich bau die Android - Variante mal in OOBDesk ein..

**Comment by nexulm** [comment]
Solved with this commit:
https://github.com/stko/oobd/commit/9976cfd261c1ae917eebdf5b7c3302b8e157cf69
