### ISSUE TITLE
Command prompt in CANraw mode delayed

### ISSUE THREAD

**Issue by nexulm** [stko/oobd#216]
Firmware init sequence:
> p 1 1 0 0
> p 8 4 0
> p 8 3 3
> p 8 2 3
> p 6 3 $FFFF
> 000001230133FF (max. delay time)

The command prompt need now up to 2s for returning!
.
>

**Comment by stko** [comment]
It's a feature, not a bug:-)
It's made to let the application know when the sequence is done by delaying the prompt until it's end

**Comment by nexulm** [comment]
OK, but it doesn't make sense in continuously mode, or?
My expectation is that the frame is fired out directly and with the delay-/cycletime afterwards without delaying the command prompt.
Maybe all of us will run in some trouble by creating our own lua script files due to hande this behaviour!?!
