### ISSUE TITLE
serWriteDisplay() uses wrong coding (under Windows?)

### ISSUE THREAD

**Issue by stko** [stko/oobd#223]
When writing text via serWriteDisplay() to a file, special characters are not UTF-8, but ANSI encoded

**Comment by nexulm** [comment]
For me it's more an issue for the whole document by opening the document as ANSI-encoded document and not as UTF-8 encoded document. In combination with an xslt file if XML file struture is used as output the browser is not showing the document if the XML file is ANSI-encoded.

**Comment by stko** [comment]
Fixed in https://github.com/stko/oobd/commit/95a94af608c0e0e9b4aa7ca3726f369fe9fa73db
