### ISSUE TITLE
Missing "Menu" item on some devices which have hardware buttons

### ISSUE THREAD

**Issue by nexulm** [stko/oobd#226]
On Samsung Tab4 you have three "hardware" buttons but not including a "menu" button so you're not able to open the OOBD seetings menu so that you are not able to configure anything (BT-Interface, WEBui enable/disable), ...

**Comment by stko** [comment]
Could you please try what happens if you press the "task switch" soft botton longer? For my device it works that way

(http://android.stackexchange.com/questions/81597/cant-open-menu-in-apps-without-a-menu-button-or-physical-key)

**Comment by nexulm** [comment]
Argh, I've learned something again. Why didn't find Nico this hint years ago. :-(
