### ISSUE TITLE
;Classloader-property defaults funktionieren nicht;Core;stko;accepted;stko;None

### ISSUE THREAD

**Issue by GoogleCodeExporter** [stko/oobd#68]
```
defect
```

Original issue reported on code.google.com by `michael....@gmail.com` on 27 Jun 2012 at 10:12

**Comment by stko** [comment]
für die Klassen UIHandler und Scriptengine werden die zu ladenden Klassen schon aus der Resource-Datei classloader.cfg gelesen, d.h. für die beiden sind schon mal keine core.props- Einträge oder dummy-Verzeichnisse notwendig. Für die ausstehenden Klassen (protocol, db usw.) ist das noch nachzuholen..
