### ISSUE TITLE
;Überprüfen aller Thread- Runs auf sinnloses Verbraten von Rechenzeit;Core;stko;closed;stko;fixed

### ISSUE THREAD

**Issue by GoogleCodeExporter** [stko/oobd#84]
```
defect
```

Original issue reported on code.google.com by `michael....@gmail.com` on 27 Jun 2012 at 10:12

**Comment by stko** [comment]
I can roughly remember that we removed some empty loops- we still need a overall check of the thread management, but this particular item we can close
